DROP VIEW ADMIN.VIEW_AJUSTE_APLICACAO_AGUA_MENSAL;
DROP VIEW VIEW_LEITURA_NPK_PH_UMIDADE_CULTURA_ANUAL;
DROP VIEW VIEW_AJUSTE_APLICACAO_NUTRIENTES;
DROP VIEW VIEW_CLASSIFICACAO_NPK_PH_UMIDADE_CULTURA_ANUAL;
DROP TABLE ADMIN.AJUSTE_APLICACAO;
DROP TABLE ADMIN.LEITURA_SENSOR;
DROP TABLE ADMIN.CULTURA;
DROP TABLE ADMIN.SENSOR;