DROP VIEW ADMIN.VIEW_AJUSTE_APLICACAO_MENSAL;
DROP VIEW ADMIN.VIEW_LEITURA_PH_ANUAL;
DROP TABLE ADMIN.AJUSTE_APLICACAO;
DROP TABLE ADMIN.LEITURA_SENSOR;
DROP TABLE ADMIN.CULTURA;
DROP TABLE ADMIN.SENSOR;